{
  self {
    username
    email
    employee {
      id
      name
      post
      phone
      area
      am {
        id
        name
      }
      rsm {
        id
        name
      }
      md {
        id
        name
      }
    }
  }
}
