query Invoices($data: JSON!) {
  invoices(where: $data, sort: "confirmed_at:DESC", limit: -1) {
    id
    index
    confirmed
    confirmed_at
    createdAt
    cash_total
    credit_total
    dealer {
      id
      name
      address
    }
    officer {
      id
      name
      am {
        id
        name
      }
      rsm {
        id
        name
      }
    }
  }
}
