query Transactions($data: JSON!) {
  transactions(where: $data, sort: "date:DESC") {
    id
    amount
    mr_no
    date
    dealer {
      id
      name
    }
    officer {
      id
      name
      am {
        id
        name
      }
      rsm {
        id
        name
      }
    }
    summary
    confirmed
    createdAt
  }
}
